//
// Created by nicholas on 01/12/2025.
//

#ifndef EQUATION_SOLVER_TESTMULTIPLICATIONSIMPLIFIER_H
#define EQUATION_SOLVER_TESTMULTIPLICATIONSIMPLIFIER_H

void testMultiplicationSimplifier_runTests();

#endif //EQUATION_SOLVER_TESTMULTIPLICATIONSIMPLIFIER_H