//
// Created by nicholas on 19/12/2025.
//

#ifndef EQUATION_SOLVER_TESTDIVISIONSIMPLIFIER_H
#define EQUATION_SOLVER_TESTDIVISIONSIMPLIFIER_H

void testDivisionSimplifier_runTests();

#endif //EQUATION_SOLVER_TESTDIVISIONSIMPLIFIER_H