//
// Created by nicholas on 28/11/2025.
//

#ifndef EQUATION_SOLVER_TESTGRAMMARCHECKER_H
#define EQUATION_SOLVER_TESTGRAMMARCHECKER_H

void testGrammarChecker_runTests();

#endif //EQUATION_SOLVER_TESTGRAMMARCHECKER_H